In [1]:
# load the checked output CSV file
import pandas as pd

# Load the checked output CSV file
checked_df = pd.read_csv('Data/output_v2_checked.csv')
checked_df

,name,area,postcode,latitude,longitude,easting,northing
0,Barking,Barking and Dagenham,IG11 0BB,51.530000,0.088874,544992.902885,183300.180862
1,Dagenham,Barking and Dagenham,RM10 7ES,51.559469,0.157028,549623.356235,186714.188598
2,Dowgate,City,EC4R 3UE,51.510035,-0.090101,532637.238240,180740.710344
3,Shoreditch,Hackney,EC1V 9EY,51.526622,-0.085486,532909.219426,182593.568436
4,Stoke Newington,Hackney,N16 0AR,51.562572,-0.076866,533402.031897,186607.063610
...,...,...,...,...,...,...,...
98,Wandsworth,Wandsworth,SW18 1RL,51.456383,-0.201401,525060.558867,174578.738179
99,Battersea,Wandsworth,SW11 2TL,51.467115,-0.169294,527261.298771,175827.380140
100,Tooting,Wandsworth,SW17 7SQ,51.437827,-0.162705,527800.651014,172582.007009
101,Paddington,Westminster,W2 6NL,51.520072,-0.183319,526141.005267,181692.215639
102,Soho,Westminster,W1D 5ET,51.512461,-0.130089,529855.515278,180938.811858

In [2]:
# show the stations with missing British National Grid coordinates
missing_bng = checked_df[checked_df['easting'].isna() | checked_df['northing'].isna()]
missing_bng

,name,area,postcode,latitude,longitude,easting,northing
15,Hainault,Redbridge,IG6 3DY,51.606251,0.104157,NaN,NaN
23,Chingford,Waltham Forest,E4 6PP,51.629558,-0.004791,NaN,NaN
35,Euston,Camden,NW1 2DH,51.527624,-0.130774,NaN,NaN
41,Enfield,Enfield,EN1 4LA,51.660181,-0.052079,NaN,NaN
44,Hornsey,Haringey,N8 8LS,51.586510,-0.127397,NaN,NaN
54,Heston,Hounslow,TW7 4HR,51.474955,-0.343402,NaN,NaN
55,Bexley,Bexley,DA7 6BY,51.461081,0.153472,NaN,NaN
70,Lee Green,Greenwich,SE12 8ES,51.456374,0.012624,NaN,NaN
72,Deptford,Lewisham,SE8 5DB,51.484885,-0.033780,NaN,NaN
73,Forest Hill,Lewisham,SE23 1HP,51.442483,-0.045017,NaN,NaN
75,New Cross,Lewisham,SE14 5JN,51.473743,-0.049232,NaN,NaN

In [3]:
# Convert to British National Grid (EPSG:27700)
import pyproj
from pyproj import Transformer
transformer = Transformer.from_crs("EPSG:4326", "EPSG:27700", always_xy=True)
checked_df['easting'], checked_df['northing'] = transformer.transform(checked_df['longitude'].values, checked_df['latitude'].values)
checked_df

,name,area,postcode,latitude,longitude,easting,northing
0,Barking,Barking and Dagenham,IG11 0BB,51.530000,0.088874,544992.902885,183300.180862
1,Dagenham,Barking and Dagenham,RM10 7ES,51.559469,0.157028,549623.356235,186714.188598
2,Dowgate,City,EC4R 3UE,51.510035,-0.090101,532637.238240,180740.710344
3,Shoreditch,Hackney,EC1V 9EY,51.526622,-0.085486,532909.219426,182593.568436
4,Stoke Newington,Hackney,N16 0AR,51.562572,-0.076866,533402.031897,186607.063610
...,...,...,...,...,...,...,...
98,Wandsworth,Wandsworth,SW18 1RL,51.456383,-0.201401,525060.558867,174578.738179
99,Battersea,Wandsworth,SW11 2TL,51.467115,-0.169294,527261.298771,175827.380140
100,Tooting,Wandsworth,SW17 7SQ,51.437827,-0.162705,527800.651014,172582.007009
101,Paddington,Westminster,W2 6NL,51.520072,-0.183319,526141.005267,181692.215639
102,Soho,Westminster,W1D 5ET,51.512461,-0.130089,529855.515278,180938.811858

In [4]:
# save the updated DataFrame back to CSV
checked_df.to_csv('Data/output_v3.csv', index=False)